[#15] Tools page
stormgateworld/web pull request #26
Opened 2024-02-06 09:52 UTC by qlemaire22

First draft of the tools page.

I used the content Card for it but I had to make a bunch of field optional, is that OK? Should I follow another approach? 

Also, I didn't know which tools/projects you wanted to highlight so I put only one for now. I can put more if you have a list or anything.

2024-02-06 16:50 UTC, qlemaire22 commented
I can add tags like on aoeworld also. 
And I was wondering if the data should be hardcoded or if I should fetch it from some places?

2024-02-06 16:53 UTC, robertvanhoesel commented
Have to take a detailed look later but hardcoded is fine!

You can add some more tools from the community like that Replay renamer, Luminite.gg etc

2024-02-06 17:47 UTC, qlemaire22 commented
I added tags + community tools.
Here is how community tools looks like for example.

<img width="1512" alt="Screenshot 2024-02-06 at 18 46 23" src="https://github.com/stormgateworld/web/assets/23478363/7c111d31-60b0-4e74-9f76-9df10d9c70cf">

I left aligned the tags to be consistent with other Content metadata. 
I based the style of the tags to buttons + rounded borders. If you have anything else in mind I can improve it.

2024-02-06 19:18 UTC, robertvanhoesel requested changes
Looks great! Thanks, one minor thing about the headers though.

2024-02-06 19:18 UTC, robertvanhoesel commented on src/pages/tools.astro
> +    <div class="mx-auto max-w-screen-md px-4 md:px-0 py-8 gap-4 flex items-center flex-wrap justify-between">
I'm really happy with everything, except these headers.

I think you can best copy over the header from the Stats page and just replace the text.

If you want to split the tools into subheading you can copy the code that says 'Factions' as a header above the two groups of tools.

Alternatively you could just show 'offical' or 'by SGW' or something as a tag maybe. I'm fine either way

2024-02-07 07:57 UTC, qlemaire22 commented
I changed the header, here is how it looks like:

<img width="1512" alt="Screenshot 2024-02-07 at 08 54 02" src="https://github.com/stormgateworld/web/assets/23478363/521a9edb-16bd-4e8e-bc02-88fc57dffe0b">

I hope the wording is fine, I was not sure what to replace "Game" with. 
I also merged the two subdivisions as I think it is better for now since there are not so many projects. Could be revisited later.

2024-02-07 17:39 UTC, robertvanhoesel reviewed
Applied some small fixes to the alignment 👍

2024-02-07 17:40 UTC, merged